[package]
name = "tree-sitter-java"
description = "Java grammar for tree-sitter"
version = "0.21.0"
authors = [
  "Ayman Nadeem <aymannadeem@github.com>",
  "Max Brunsfeld <maxbrunsfeld@gmail.com>",
  "Amaan Qureshi <amaanq12@gmail.com>",
]
license = "MIT"
keywords = ["incremental", "parsing", "tree-sitter", "java"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter-java"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-c2rust = { git = "https://github.com/liamrosenfeld/tree-sitter", branch = "cfg-fix" }

[build-dependencies]
cc = "1.0.91"
